version: '3'

services:
  hello-world:
    image: hello-world:latest
  spring-boot-app:
    image: mariyazheltok/spring-boot-app-docker:v1.0
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://localhost:5432/productdb
      DB_USERNAME: postgres
      DB_PASSWORD: root
      DEVOPS: MariyaZheltok
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


